services:
  - name: zotel-assignment
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://zotel-assignment.onrender.com
